### ISSUE TITLE
Implement visualizer with ncurses

### ISSUE THREAD

**Issue by rizky** [rizkyario/42-corewar#15]

**Comment by rizky** [comment]
@juliantoyeo 
![Bugs](https://imgur.com/fLQcENJ.png)

**Comment by fpetras** [comment]
<img width="504" alt="unspecified_exception" src="https://user-images.githubusercontent.com/34797639/39544891-ca5ab3f4-4e4f-11e8-8f29-50d71c77cab5.png">

**Comment by rizky** [comment]
```
 ./corewar -v 1 tests/vm/overflow/test_limit.cor tests/vm/overflow/test_limit.cor tests/vm/overflow/test_limit.cor tests/vm/overflow/test_limit.cor
```
![screen shot 2018-05-03 at 3 58 42 am](https://user-images.githubusercontent.com/6814254/39557232-5b09931c-4e86-11e8-868b-0b9fea86281c.png)
