### ISSUE TITLE
Handle option [-v N]

### ISSUE THREAD

**Issue by rizky** [rizkyario/42-corewar#16]
-v N      : Verbosity levels, can be added together to enable several
                - 0 : Show only essentials
                - 1 : Show lives
                - 2 : Show cycles
                - 4 : Show operations (Params are NOT litteral ...)
                - 8 : Show deaths
                - 16 : Show PC movements (Except for jumps)

**Comment by fpetras** [comment]
<img width="619" alt="v_lvl1" src="https://user-images.githubusercontent.com/34797639/39157044-3b5074b6-4759-11e8-8ede-e59d2e31f936.png">
<img width="687" alt="v_lvl2" src="https://user-images.githubusercontent.com/34797639/39157045-3b76579e-4759-11e8-9ebe-c10dbe9e1821.png">
