### ISSUE TITLE
parser_op fails if operation has no space

### ISSUE THREAD

**Issue by rizky** [rizkyario/42-corewar#4]
such as `live%1`

`./asm -a resources/valid/no_space_between_op_and_param.s `

**Comment by rizky** [comment]
Fixed with commit b9b8046d4946778f20a87cb16fda00fe035770eb

**Comment by rizkyario** [comment]
Temporarily fixed with commit cbbcbed6202c431ac26ba5755b652183f4793054 and d51ab66e68125daea8715b138737e93568b82537
